---
title: "practice in R"
output: 
  html_document:
    highlight: "pygments"
    theme: "darkly"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

> __RECENT__

* [Plotting cancelled/delay flight paths at pilot union strike](./PilotUnionStrike.html) ---  繪製華航罷工事件影響航班的飛行路徑.
( *2019-02-19* )


***

> __PREVIOUS__

* [Implement a pre-trained YOLOv2 model - object detection](./yolov2.html) ---  實現物體偵測，利用 pre-trained YOLOv2 model.
( *2018-06-05* )

* [Carvana Image Masking - Semantic Segmentation using Keras](./carvana.html) ---  使用 Keras 影像分割，自動去除 Carvana 影像背景.
( *2018-04-23* )

* [VOC2012 - Semantic Segmentation using Keras with Tensorflow](./voc2012.html) ---  以 FCN 實現 VOC2012 語義分割，使用Keras和Tensorflow.
( *2017-11-18* )

* [CIFAR-10 - Object Recognition using Keras with Tensorflow](./cifar10.html) --- 
CIFAR-10影像辨識，使用Keras和Tensorflow.
( *2017-10-12* )

* [implementation of MLP, RNN and CNN on movie reviews sentiment analysis](./movieReviewCNN.html) --- 
實作MLP、RNN及CNN於電影評論情感分析.
( *2017-09-26* )

* [generative adversarial networks (GAN) on the MNIST dataset](./kerasGAN.html) --- 
實作生成對抗網路GAN自動生成手寫數字.
( *2017-08-08* )

* [convolutional neural networks (CNN) on the MNIST dataset](./kerasCNN.html) --- 
利用Keras實作CNN於手寫數字的辨識.
( *2017-06-21* )

* [handwritten digits recognizer with deep learning - MNIST Data](./digitRecognizer.html) --- 
利用H2O深度學習DNN於手寫數字的辨識.
( *2017-06-15* )

* [sentiment scores of movie reviews](./sentimentAnalysis.html) --- 
使用 simple matching 分析電影評論情感分數.
( *2017-05-12* )

* [movie reviews sentiment analysis - Bag of Words Meets Bags of Popcorn](./movieReviewSentiment.html) --- 
情感分析 - 電影評論正負極性.
( *2017-04-22* )

* [extracting the topics with LDA](./stspMailTopics.html) --- 
使用 LDA 擷取主題 - 以網站意見信箱為例.
( *2017-03-14* )

* [text classiﬁcation in opinion mining of the website](./stspMailService.html) --- 
文本分類應用 - 以網站意見信箱為例.
( *2017-03-03* )

* [thematic maps of Kaohsiung city public bike](./kaoCityBike.html) --- 
利用 tmap 套件產出主題地圖 - 以高雄市公共腳踏車為例.
( *2017-01-25* )

* [exploring association rules with Apriori](./associationRules.html) --- 
運用 Apriori 產生關聯規則.
( *2017-01-18* )

* [logistic regression with Artpiece data](./logisticRegression.html) --- 
glm 邏輯迴歸分析.
( *2017-01-13* )

* [multiple linear regression analysis](./linearRegression.html) --- 
多元線性迴歸分析.
( *2017-01-05* )

* [data exploration with SparkR 2.0.2](./exerciseSparkR.html) --- 
使用 SparkR 2.0.2 進行數據探索.
( *2016-12-15* )

* [boosting in ensembles using the caret package](./ensembleBoosting.html) --- 
Ensemble modeling，以 GBM (Gradient Boosted Machine) 和 XGBoost (eXtreme Gradient Boosting) 為例.
( *2016-12-13* )

* [cross-validation and classification using the caret package](./classifyWhiskies.html) --- 
使用 caret 套件交叉驗證、分類學習，以 C5.0, Neural Networks, SVM, Naive Bayes, Random Forests and k-NN 為主.
( *2016-11-25* )

* [scotch whiskies flavour mapping with MDS](./mdsWhiskies.html) --- 
利用 MDS 方法繪製 Scotch Whiskies Flavour Map. 
( *2016-11-21* )

* [scotch whiskies flavour mapping with PCA](./pcaWhiskies.html) --- 
利用 PCA 方法繪製 Scotch Whiskies Flavour Map. 
( *2016-11-14* )

* [k-means cluster analysis of scotch whiskies](./kmeansWhiskies.html) --- 
Extract 網頁資訊、利用 K-means 分群法對 Scotch Whiskies 進行分群、以 Google Map 展現. 
( *2016-11-08* )

* [create a website through RStudio](./createWebsite.html) --- 
利用 RStudio 進行 Git 版本控管、R Markdown 產出 HTML 網頁至 Github. 
( *2016-11-03* )
